# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Timeout for commands executed by starship (ms)
command_timeout = 1000

[hostname]
ssh_only = false
disabled = false
