[colors.bright]
black = "0x002b36"
blue = "0x839496"
cyan = "0x93a1a1"
green = "0x586e75"
magenta = "0x6c71c4"
red = "0xcb4b16"
white = "0xfdf6e3"
yellow = "0x657b83"

[colors.normal]
black = "0x073642"
blue = "0x268bd2"
cyan = "0x2aa198"
green = "0x859900"
magenta = "0xd33682"
red = "0xdc322f"
white = "0xeee8d5"
yellow = "0xb58900"

[colors.primary]
background = "0x002b36"
foreground = "0x839496"

[font]
size = 13.0

[font.normal]
family = "MonoLisa Nerd Font"

[terminal.shell]
args = ["--login", "-c", "/usr/local/bin/tmux attach || /usr/local/bin/tmux new -s 'Alacritty'"]
program = "/usr/local/bin/fish"

[[keyboard.bindings]]
key = "t"
mods = "Command"
chars = "\u0001\u0063"

[[keyboard.bindings]]
key = "w"
mods = "Command"
chars = "\u0001\u0078"

[[keyboard.bindings]]
key = "Key1"
mods = "Command"
chars = "\u0001\u0031"

[[keyboard.bindings]]
key = "Key2"
mods = "Command"
chars = "\u0001\u0032"

[[keyboard.bindings]]
key = "Key3"
mods = "Command"
chars = "\u0001\u0033"

[[keyboard.bindings]]
key = "Key4"
mods = "Command"
chars = "\u0001\u0034"

[[keyboard.bindings]]
key = "Key5"
mods = "Command"
chars = "\u0001\u0035"

[[keyboard.bindings]]
key = "Key6"
mods = "Command"
chars = "\u0001\u0036"

[[keyboard.bindings]]
key = "Key7"
mods = "Command"
chars = "\u0001\u0037"

[[keyboard.bindings]]
key = "Key8"
mods = "Command"
chars = "\u0001\u0038"

[[keyboard.bindings]]
key = "Key9"
mods = "Command"
chars = "\u0001\u0039"

[[keyboard.bindings]]
key = "D"
mods = "Command"
chars = "\u0001\u0025"

[[keyboard.bindings]]
key = "D"
mods = "Command|Shift"
chars = "\u0001\u0022"
