[colors.bright]
black = "0x002b36"
blue = "0x839496"
cyan = "0x93a1a1"
green = "0x586e75"
magenta = "0x6c71c4"
red = "0xcb4b16"
white = "0xfdf6e3"
yellow = "0x657b83"

[colors.normal]
black = "0x073642"
blue = "0x268bd2"
cyan = "0x2aa198"
green = "0x859900"
magenta = "0xd33682"
red = "0xdc322f"
white = "0xeee8d5"
yellow = "0xb58900"

[colors.primary]
background = "0x002b36"
foreground = "0x839496"

[font]
size = 13.0

[font.normal]
family = "Source Code Pro for Powerline"

[shell]
args = ["--login", "-c", "/usr/local/bin/tmux attach || /usr/local/bin/tmux new -s 'Alacritty'"]
program = "/usr/local/bin/fish"
